#!/bin/sh
export ASAN_OPTIONS="abort_on_error=1 detect_leaks=0 symbolize=0 allocator_may_return_null=1"
export AFL_CC="gcc"
AFL_USE_ASAN=1 make -j4 -s -C src
AFL_USE_ASAN=1 make -j4 -s -C programs dwgrewrite
performance

LD_LIBRARY_PATH=`pwd`/src/.libs \
  afl-fuzz -d -m none -i ../.fuzz-in -o .fuzz-out \
    programs/.libs/dwgrewrite -y -v0 @@ /dev/null
